"""phase 5+6+8: rename claude_request_id, add is_paused, payment_events, content_deliveries, admin_actions

Revision ID: 285d2e983578
Revises: f736253da5f7
Create Date: 2026-04-26 21:15:34.743515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285d2e983578'
down_revision: Union[str, Sequence[str], None] = 'f736253da5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('target_fan_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_target_fan_id'), ['target_fan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_timestamp'), ['timestamp'], unique=False)

    op.create_table('content_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fan_id', sa.BigInteger(), nullable=False),
    sa.Column('sales_attempt_id', sa.Integer(), nullable=True),
    sa.Column('content_set_id', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_set_id'], ['content_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fan_id'], ['clients.fan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_attempt_id'], ['sales_attempts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_deliveries_content_set_id'), ['content_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_deliveries_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_deliveries_fan_id'), ['fan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_deliveries_sales_attempt_id'), ['sales_attempt_id'], unique=False)

    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fan_id', sa.BigInteger(), nullable=False),
    sa.Column('sales_attempt_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('invoice_payload', sa.String(length=128), nullable=True),
    sa.Column('telegram_charge_id', sa.String(length=128), nullable=True),
    sa.Column('provider_charge_id', sa.String(length=128), nullable=True),
    sa.Column('amount_stars', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('payload_raw', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['clients.fan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_attempt_id'], ['sales_attempts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_fan_id'), ['fan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_invoice_payload'), ['invoice_payload'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_sales_attempt_id'), ['sales_attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_telegram_charge_id'), ['telegram_charge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        # Existing rows must default to "not paused"; server_default makes the
        # not-null backfill safe across SQLite/Postgres.
        batch_op.add_column(
            sa.Column('is_paused', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('paused_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_request_id', sa.String(length=128), nullable=True))
        batch_op.drop_column('claude_request_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claude_request_id', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('llm_request_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('paused_reason')
        batch_op.drop_column('is_paused')

    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_payment_events_telegram_charge_id'))
        batch_op.drop_index(batch_op.f('ix_payment_events_sales_attempt_id'))
        batch_op.drop_index(batch_op.f('ix_payment_events_invoice_payload'))
        batch_op.drop_index(batch_op.f('ix_payment_events_fan_id'))
        batch_op.drop_index(batch_op.f('ix_payment_events_event_type'))

    op.drop_table('payment_events')
    with op.batch_alter_table('content_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_deliveries_sales_attempt_id'))
        batch_op.drop_index(batch_op.f('ix_content_deliveries_fan_id'))
        batch_op.drop_index(batch_op.f('ix_content_deliveries_delivered_at'))
        batch_op.drop_index(batch_op.f('ix_content_deliveries_content_set_id'))

    op.drop_table('content_deliveries')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_target_fan_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_action_type'))

    op.drop_table('admin_actions')
    # ### end Alembic commands ###
