"""initial schema: clients, messages, facts, content_sets, sales_attempts, followups, events_log

Revision ID: f736253da5f7
Revises: 
Create Date: 2026-04-26 14:12:24.367609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f736253da5f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('fan_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('known_name', sa.String(length=128), nullable=True),
    sa.Column('fan_type', sa.String(length=8), nullable=True),
    sa.Column('type_confidence', sa.String(length=8), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'HOT', 'DORMANT', 'GHOST', 'LOST', 'BLOCKED', name='fanstatus'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('timezone_guess', sa.String(length=32), nullable=True),
    sa.Column('country_guess', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_spend_30d', sa.Float(), nullable=False),
    sa.Column('total_spend_lifetime', sa.Float(), nullable=False),
    sa.Column('ltv_estimate', sa.Float(), nullable=False),
    sa.Column('preferred_grain', sa.String(length=64), nullable=True),
    sa.Column('sales_status', sa.Enum('ACTIVE', 'PAUSED_72H', 'PAUSED_14D', 'PAUSED_PERMANENT', name='salesstatus'), nullable=False),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fan_id')
    )
    op.create_table('content_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=True),
    sa.Column('price_stars', sa.Integer(), nullable=False),
    sa.Column('price_usd_equivalent', sa.Float(), nullable=False),
    sa.Column('files_path', sa.Text(), nullable=True),
    sa.Column('preview_path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_types', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('events_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fan_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_log_fan_id'), ['fan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('followups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fan_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['clients.fan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followups_fan_id'), ['fan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fan_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('direction', sa.Enum('INCOMING', 'OUTGOING', name='messagedirection'), nullable=False),
    sa.Column('media_type', sa.Enum('TEXT', 'PHOTO', 'VIDEO', 'VOICE', 'VIDEO_NOTE', 'DOCUMENT', 'STICKER', 'OTHER', name='messagemediatype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_grain', sa.String(length=8), nullable=True),
    sa.Column('used_playbook', sa.String(length=64), nullable=True),
    sa.Column('claude_request_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['clients.fan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_fan_id'), ['fan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    op.create_table('sales_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fan_id', sa.BigInteger(), nullable=False),
    sa.Column('content_set_id', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.Enum('SENT', 'OPENED', 'PURCHASED', 'DECLINED', 'IGNORED', 'REFUNDED', name='saleoutcome'), nullable=False),
    sa.Column('amount_stars', sa.Integer(), nullable=False),
    sa.Column('amount_usd_equivalent', sa.Float(), nullable=False),
    sa.Column('invoice_payload', sa.String(length=128), nullable=True),
    sa.Column('grain_used', sa.String(length=8), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('reason_failed', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_set_id'], ['content_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fan_id'], ['clients.fan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_attempts_fan_id'), ['fan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_attempts_invoice_payload'), ['invoice_payload'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fan_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('date_disclosed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['clients.fan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fan_id', 'key', name='uq_facts_fan_key')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_fan_id'), ['fan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_fan_id'))

    op.drop_table('facts')
    with op.batch_alter_table('sales_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_attempts_invoice_payload'))
        batch_op.drop_index(batch_op.f('ix_sales_attempts_fan_id'))
        batch_op.drop_index(batch_op.f('ix_sales_attempts_attempted_at'))

    op.drop_table('sales_attempts')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_fan_id'))

    op.drop_table('messages')
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followups_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_followups_fan_id'))

    op.drop_table('followups')
    with op.batch_alter_table('events_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_events_log_fan_id'))
        batch_op.drop_index(batch_op.f('ix_events_log_event_type'))

    op.drop_table('events_log')
    op.drop_table('content_sets')
    op.drop_table('clients')
    # ### end Alembic commands ###
